[workspace]
members = ["jasn", "jasn-core", "jaml"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["Akash Rakholia"]
license = "MIT"
repository = "https://github.com/arakholia/jasn-rs"
